import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import HeaderMain from "@/components/product_details/HeaderMain";
// import NavBar from "@/components/product_details/NavBar";
// import ProductDetail from "@/components/product_details/ProductDetail";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ShopSmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <HeaderMain />
        <NavBar/> */}
        {children}
      </body>
    </html>
  );
}
